# Generated by Django 5.2.6 on 2026-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('sneakers', 'Sneakers'), ('running', 'Running'), ('casual', 'Casual'), ('boots', 'Boots')], default='sneakers', max_length=20),
        ),
    ]
