# Generated by Django 5.2.6 on 2026-04-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('sneakers', 'Sneakers'), ('running', 'Running'), ('casual', 'Casual'), ('boots', 'Boots'), ('heels', 'Heels')], default='sneakers', max_length=20),
        ),
    ]
