# Generated by Django 6.0.3 on 2026-06-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='stock',
        ),
        migrations.AddField(
            model_name='shoe',
            name='is_new_launch',
            field=models.BooleanField(default=False, help_text='Show this shoe in the New Launch spotlight on the homepage.', verbose_name='⭐ New Launch'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='is_timely_shop',
            field=models.BooleanField(default=False, help_text='Show this shoe in the Timely Shop featured section.', verbose_name='🕐 Timely Shop'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='availability_end',
            field=models.DateTimeField(blank=True, help_text='Optional: hide from Timely Shop after this date/time.', null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='availability_start',
            field=models.DateTimeField(blank=True, help_text='Optional: hide from Timely Shop before this date/time.', null=True),
        ),
        migrations.CreateModel(
            name='ShoeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shoes/variants/')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shoes.shoe')),
            ],
            options={
                'ordering': ['color', 'size'],
                'unique_together': {('shoe', 'color', 'size')},
            },
        ),
    ]
