# Generated by Django 6.0.3 on 2026-06-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_shoe_options_remove_shoe_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='availability_end',
            field=models.DateTimeField(blank=True, help_text='Optional: hide from Timely Shop after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='availability_start',
            field=models.DateTimeField(blank=True, help_text='Optional: hide from Timely Shop before this date.', null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='is_new_launch',
            field=models.BooleanField(default=False, help_text='Show in homepage spotlight. Only one shoe should have this ticked.', verbose_name='⭐ New Launch'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='is_timely_shop',
            field=models.BooleanField(default=False, help_text='Show in the homepage Timely Shop featured strip.', verbose_name='🕐 Timely Shop'),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='color',
            field=models.CharField(help_text='e.g. Black, White, Red, Navy', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo showing this specific colour. Leave blank to use the main shoe image.', null=True, upload_to='shoes/variants/'),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='size',
            field=models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42')], help_text='EU size — enter how many units you have in stock below.', max_length=5),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of pairs available for this colour + size.'),
        ),
    ]
