# Generated by Django 6.0.3 on 2026-06-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_shoe_availability_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Black, White, Red. Each color is its own shoe entry.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for this color.', null=True, upload_to='shoes/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='is_new_launch',
            field=models.BooleanField(default=False, help_text='Tick to feature this shoe in the New Launch spotlight. Only one shoe should be ticked.', verbose_name='⭐ New Launch'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='is_timely_shop',
            field=models.BooleanField(default=False, help_text='Tick to include this shoe in the Timely Shop featured strip.', verbose_name='🕐 Timely Shop'),
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('6', 'US 6'), ('6.5', 'US 6.5'), ('7', 'US 7'), ('7.5', 'US 7.5'), ('8', 'US 8'), ('8.5', 'US 8.5'), ('9', 'US 9'), ('9.5', 'US 9.5'), ('10', 'US 10'), ('10.5', 'US 10.5'), ('11', 'US 11'), ('12', 'US 12')], max_length=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Units available for this size.')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shoes.shoe')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('shoe', 'size')},
            },
        ),
        migrations.DeleteModel(
            name='ShoeVariant',
        ),
    ]
